# Numpy Exercise  <img src = "numpy1.png">
###### Authored by T.K.Senthil Kumar

#### 1. Create a numpy array with the number of elements equals your age. The value of array elements is a random number between 10 to your age 

In [1]:
#Solution

import numpy as np
nparray = np.random.randint(10,23,23)
print(nparray)


[13 15 11 15 11 21 13 15 10 13 14 10 20 14 12 18 12 19 16 21 19 12 20]


#### 2. Create a numpy array between 1 to 50 with the span(space) of 2 and print the length of the array

In [2]:
# Solution

nparray = np.arange(1, 50, 2)
print(nparray)
print(len(nparray))


[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49]
25


#### 3. Create an equally spaced numpy array with 27 elements between 4 and 7 

In [3]:
# Solution

nparray = np.linspace(4, 7, 27)
print(nparray)


[4.         4.11538462 4.23076923 4.34615385 4.46153846 4.57692308
 4.69230769 4.80769231 4.92307692 5.03846154 5.15384615 5.26923077
 5.38461538 5.5        5.61538462 5.73076923 5.84615385 5.96153846
 6.07692308 6.19230769 6.30769231 6.42307692 6.53846154 6.65384615
 6.76923077 6.88461538 7.        ]


#### 4. Create a matrix of size (5 x 4) with random numbers and round off the each elements by only 2 fractional points.

In [4]:
# Solution

nparray = np.random.rand(5,4)
nparray = np.around(nparray, decimals=2)
print(nparray)

[[0.39 0.9  0.03 0.21]
 [0.9  0.73 0.38 0.07]
 [0.02 0.83 0.04 0.75]
 [0.08 0.46 0.58 0.2 ]
 [0.29 0.85 0.98 0.9 ]]


#### 5. Create a matrix of size (5x5) with random integers between 5 to 15

In [5]:
# Solution

nparray = np.random.randint(5,16,(5,5))
print(nparray)

[[ 7 15 11 13  9]
 [15 12  6 12 11]
 [ 6 15  8 12  8]
 [13  7 12 12 15]
 [14  6 13  7 14]]


#### 6. Create the one dimensional array of zeros of random length below 20 with the data type int32

In [6]:
# Solution

nparray = np.zeros(np.random.randint(20),dtype='int32')
print(nparray)


[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


#### 7. Create a two dimensional array of ones of random row and column lengths with the data type of float32 

In [7]:
# Solution

nparray = np.ones((np.random.randint(20),np.random.randint(20)),dtype='float32')
print(nparray)


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


#### 8. Create a matrix exactly as same as shown below and print its shape, type and dtype
<img src = "np_mat1.png">

In [8]:
# Solution

nparray = np.array(([9, 25, 50, 34, 45], [3, 34, 34, 65, 2], [5, 7, 3, 76, 3], [7, 8, 6, 54, 6], [23, 12, 8, 5, 8]))
print(nparray.shape)
print(type(nparray))
print(nparray.dtype)


(5, 5)
<class 'numpy.ndarray'>
int64


#### 9. Access the center pixel of the matrix defined in the question no 8 ( Don't enter the row and column index explicitely)

In [9]:
# Solution

row = int(len(nparray)/2)
coloumn = int(len(nparray.T)/2)
print(nparray[row,coloumn])


3


#### 10. Print the all the elements of 3rd row of the matrix

In [10]:
# Solution

print(nparray[2,:])


[ 5  7  3 76  3]


#### 11. Print the all the elements of 4th columns of the matrix

In [11]:
# Solution

print(nparray[:,3])


[34 65 76 54  5]


#### 12. Print the 4 corner pixels of the matrix

In [12]:
# Solution

print("The 4 corner pixels of matrix is ", nparray[0,0], nparray[0,-1], nparray[-1,0], nparray[-1,-1])


The 4 corner pixels of matrix is  9 45 23 8


#### 13. Create three matrix m1,m2,m3 with the elements grouped in the figure below
<img src = "np_mat2.png">

In [13]:
# Solution 

m1 = nparray[:2, 2:-1]
m2 = nparray[3:, :2]
m3 = nparray[2:,2:]
print("m1 = ", m1, "\nm2 = ", m2, "\nm3 = ", m3)


m1 =  [[50 34]
 [34 65]] 
m2 =  [[ 7  8]
 [23 12]] 
m3 =  [[ 3 76  3]
 [ 6 54  6]
 [ 8  5  8]]


#### 14. Reshape all the three matrix segmented in the above task in to three  1-dimensional vector.

In [14]:
# Solution

m1 = m1.flatten()
m2 = m2.flatten()
m3 = m3.flatten()
print("\nConverting using flatten (for converting to perfect 1D array)")
print("m1 = ", m1, "\nm2 = ", m2, "\nm3 = ", m3)

m1 = nparray[:2, 2:-1]
m2 = nparray[3:, :2]    # for getting the old values of m1,m2,m3
m3 = nparray[2:,2:]

m1 = m1.reshape(1,4)
m2 = m2.reshape(1,4)
m3 = m3.reshape(1,9)
print("Converting using reshape")
print("m1 = ", m1, "\nm2 = ", m2, "\nm3 = ", m3)



Converting using flatten (for converting to perfect 1D array)
m1 =  [50 34 34 65] 
m2 =  [ 7  8 23 12] 
m3 =  [ 3 76  3  6 54  6  8  5  8]
Converting using reshape
m1 =  [[50 34 34 65]] 
m2 =  [[ 7  8 23 12]] 
m3 =  [[ 3 76  3  6 54  6  8  5  8]]


#### 15. Concatenate the matrix m1 and m2 in both vertical and horizontal direction

In [15]:
# Solution

print("Concatenation in horizontal of m1 and m2 is ", np.concatenate((m1,m2), axis=1))
print("Concatenation in vertical of m1 and m2 is ", np.concatenate((m1,m2)))


Concatenation in horizontal of m1 and m2 is  [[50 34 34 65  7  8 23 12]]
Concatenation in vertical of m1 and m2 is  [[50 34 34 65]
 [ 7  8 23 12]]


#### 16. Add, Subtract, multiply, divide the matrixes m1 and m2

In [16]:
# Solution

print("Addition of m1 and m2 is ", m1+m2)
print("Subtraction of m1 and m2 is ", m1-m2)
print("Multiplication of m1 and m2 is ", m1*m2)
print("Division of m1 and m2 is ", m1/m2)


Addition of m1 and m2 is  [[57 42 57 77]]
Subtraction of m1 and m2 is  [[43 26 11 53]]
Multiplication of m1 and m2 is  [[350 272 782 780]]
Division of m1 and m2 is  [[7.14285714 4.25       1.47826087 5.41666667]]


#### 17. Add the m1 with m3 by removing the first row and last column of m3

In [17]:
# Solution

m1 = nparray[:2, 2:-1]
m3 = nparray[2:,2:]  # for getting the old values of m1, m3
m3 = m3[1:,:2]
print("Addition of m1 and m3 after removing the first row and last column of m3", m1+m3)


Addition of m1 and m3 after removing the first row and last column of m3 [[56 88]
 [42 70]]


#### 18. Form the matrix m4 by concatenating (as a new row) the vector [me1, me2] with the matrix m1, where me1 and me2 are the mean values of each column on m1.

In [18]:
# Solution

m4 = m1.mean(axis=0)
m4 = m4.reshape((1, 2))
m4 = np.concatenate((m1,m4), axis=0)
print(m4)


[[50.  34. ]
 [34.  65. ]
 [42.  49.5]]


#### 19. Perform the matrix multiplication between m3 and m4

In [19]:
# Solution

print(np.matmul(m4,m3))


[[ 572.  2870. ]
 [ 724.  2161. ]
 [ 648.  2515.5]]


#### 20. Compute the maximum and minimum value of mean, variance, standard deviation for each row of matrix created in question number 8.

In [20]:
# Solution

nparray = np.array(([9, 25, 50, 34, 45], [3, 34, 34, 65, 2], [5, 7, 3, 76, 3], [7, 8, 6, 54, 6], [23, 12, 8, 5, 8]))
print(nparray)
mean = nparray.mean(axis=1)
variance = nparray.var(axis=1)
std = nparray.std(axis=1)
print("Mean is: ",mean,"\nMax of mean is:",np.max(mean),"\nMin of mean is: ",np.min(mean))
print("\nVariance is: ", variance,"\nMax of variance is:",np.max(variance),"\nMin of variance is: ",np.min(variance))
print("\nStandard Deviation is: ", std,"\nMax of std is:",np.max(std),"\nMin of std is: ",np.min(std))


[[ 9 25 50 34 45]
 [ 3 34 34 65  2]
 [ 5  7  3 76  3]
 [ 7  8  6 54  6]
 [23 12  8  5  8]]
Mean is:  [32.6 27.6 18.8 16.2 11.2] 
Max of mean is: 32.6 
Min of mean is:  11.2

Variance is:  [214.64 548.24 820.16 357.76  39.76] 
Max of variance is: 820.1600000000001 
Min of variance is:  39.760000000000005

Standard Deviation is:  [14.65059726 23.41452541 28.63843571 18.91454467  6.30555311] 
Max of std is: 28.63843571147 
Min of std is:  6.305553108173779


#### 21. Compute the average and strike rate for each player and sort it decending way (seperately for avg and strike rate)
<img src = 'crick1.png'>

In [21]:
# Solution 

runs = np.array([[54,60,10,65],[102,2,78,32],[3,110,1,92],[56,6,12,42],[12,8,22,11]])
balls = np.array([[50,42,22,78],[95,8,65,43],[9,100,7,101],[27,3,11,31],[24,20,36,27]])
strike_rate = runs/balls*100
print(strike_rate)
print("Average of each player runs and sorted in decending is : ",np.sort(runs.mean(axis=1))[::-1])
print("Average of each player strike rate and sorted in decending is : ",np.sort(strike_rate.mean(axis=1))[::-1])


[[108.         142.85714286  45.45454545  83.33333333]
 [107.36842105  25.         120.          74.41860465]
 [ 33.33333333 110.          14.28571429  91.08910891]
 [207.40740741 200.         109.09090909 135.48387097]
 [ 50.          40.          61.11111111  40.74074074]]
Average of each player runs and sorted in decending is :  [53.5  51.5  47.25 29.   13.25]
Average of each player strike rate and sorted in decending is :  [162.99554687  94.91125541  81.69675643  62.17703913  47.96296296]


#### 22. The students mark was recorded in a numpy array: marks = np.array([65,84,47,56,89,98,48,77,80,39]).  Cutoff for pass is 50 marks. Write the logic to print the number of students passed and failed. 

In [22]:
# Solution

marks = np.array([65,84,47,56,89,98,48,77,80,39])
print("Number of students passed is ", len(marks[np.where(marks>=50)]))
print("Number of students failed is ", len(marks[np.where(marks<50)]))


Number of students passed is  7
Number of students failed is  3


#### 23. The class incharge decided to give a mercy mark of 5 for those who scored between 45 and 49. Also the bonus of 5 marks awarded to the students who scored more than 80. Print all the student marks and compute the increase in the pass percentage of class. Any score more than 100 must be recorded as only 100.

In [23]:
# Solution

print("Before adding mercy and bonus marks : ", marks)
pass_percent = (marks[np.where(marks>=50)].size/marks.size)*100
index = np.where(np.logical_or(np.logical_and(marks>=45,marks<=49),marks>80))
marks[index] = marks[index]+5
marks[np.where(marks>100)] = 100
print("After adding marks : ", marks)
new_percent = (marks[np.where(marks>=50)].size/marks.size)*100
print("Percentage increase after giving mercy marks is ",(new_percent-pass_percent)/pass_percent*100,"%")


Before adding mercy and bonus marks :  [65 84 47 56 89 98 48 77 80 39]
After adding marks :  [ 65  89  52  56  94 100  53  77  80  39]
Percentage increase after giving mercy marks is  28.57142857142857 %


#### 24. Print the time taken for performing the following operation using list and numpy array
####       (x(i)^2 +8) / y(i),   where x and y are real integers from 1 to 60000

In [24]:
# Solution

import time
print("Using list")
start = time.process_time()
x = list(range(1,60001))
y = list(range(1,60001))
i = 5
for x,y in zip(x,y):
    expression = (x*(i**2)+8)/(y*i)
print("Time taken for executing using list is ", time.process_time()-start)

print("Using numpy array")
start = time.process_time()
x = y = np.arange(1,60001,1)
expression = (x*(i**2)+8)/(y*i)
print("Time taken for executing using numpy array is ", time.process_time()-start)



Using list
Time taken for executing using list is  0.05349400000000004
Using numpy array
Time taken for executing using numpy array is  0.002402999999999933


#### 25. Create a Github account and upload your solution with the short write-up on Numpy

# Solution

https://github.com/akashla500/Mtech_AI_PDS.git

